<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref } from 'vue'
import * as THREE from 'three'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'
import { calculatePlaneCubeIntersections, calculatePlaneGeometryIntersections, createPlaneFromEquation, type CuttingPreset } from './cutting'
import { cuttingPresets } from './presets'
type Shape='cube'|'prism'|'triangular'|'cylinder'|'cone'
const geometries=[{id:'cube',name:'正方体',subtitle:'Cube',icon:'◇'},{id:'prism',name:'长方体',subtitle:'Rectangular prism',icon:'▱'},{id:'triangular',name:'三棱柱',subtitle:'Triangular prism',icon:'△'},{id:'cylinder',name:'圆柱',subtitle:'Cylinder',icon:'○'},{id:'cone',name:'圆锥',subtitle:'Cone',icon:'△'}] as const
const selected=ref<Shape|null>(null),host=ref<HTMLDivElement>(),showSection=ref(true),activePreset=ref('')
const selectedName=computed(()=>geometries.find(g=>g.id===selected.value)?.name??'')
const visiblePresets=computed(()=>cuttingPresets.filter(p=>p.shape===selected.value))
let scene:THREE.Scene,camera:THREE.PerspectiveCamera,renderer:THREE.WebGLRenderer,controls:OrbitControls,solid:THREE.Mesh,edges:THREE.LineSegments,section:THREE.Mesh,sectionEdge:THREE.LineLoop,clipPlane:THREE.Plane
let ready=false,frame=0,cameraFrame=0
function shapeGeometry(shape:Shape){if(shape==='cube')return new THREE.BoxGeometry(2,2,2);if(shape==='prism')return new THREE.BoxGeometry(3,1.8,2);if(shape==='triangular'){const g=new THREE.CylinderGeometry(1,1,2.4,3);g.rotateX(Math.PI/2);return g}if(shape==='cylinder')return new THREE.CylinderGeometry(1,1,2.4,48);return new THREE.ConeGeometry(1.1,2.4,48)}
function initScene(){if(!host.value)return;scene=new THREE.Scene();scene.background=new THREE.Color('#f7faff');camera=new THREE.PerspectiveCamera(42,host.value.clientWidth/host.value.clientHeight,.1,100);camera.position.set(5,4,6);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(devicePixelRatio);renderer.setSize(host.value.clientWidth,host.value.clientHeight);renderer.localClippingEnabled=true;host.value.appendChild(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;scene.add(new THREE.HemisphereLight(0xffffff,0x9bbbe0,2.5));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(4,7,6);scene.add(light,new THREE.GridHelper(9,9,0xd7e4f4,0xe7eef8).translateY(-1.25));clipPlane=createPlaneFromEquation(1,0,0,10);solid=new THREE.Mesh();edges=new THREE.LineSegments();section=new THREE.Mesh();sectionEdge=new THREE.LineLoop();scene.add(solid,edges,section,sectionEdge);ready=true;window.addEventListener('resize',resize);renderLoop()}
function setModel(shape:Shape){const g=shapeGeometry(shape);solid.geometry?.dispose();edges.geometry?.dispose();solid.geometry=g;solid.material=new THREE.MeshBasicMaterial({color:0xd5d9df,transparent:true,opacity:.25,side:THREE.DoubleSide,depthWrite:false});solid.renderOrder=0;edges.geometry=new THREE.EdgesGeometry(g);edges.material=new THREE.LineBasicMaterial({color:0x334155,linewidth:3});edges.renderOrder=3;section.visible=false;sectionEdge.visible=false}
function updateCuttingPlane(preset:CuttingPreset){const [a,b,c]=preset.plane.normal;clipPlane=createPlaneFromEquation(a,b,c,preset.plane.constant)}
function updateSectionMesh(preset:CuttingPreset){const points=preset.shape==='cube'?calculatePlaneCubeIntersections(preset.plane.normal,preset.plane.constant):calculatePlaneGeometryIntersections(solid.geometry,preset.plane.normal,preset.plane.constant);if(points.length<3){section.visible=false;sectionEdge.visible=false;return}const indices:number[]=[];for(let i=1;i<points.length-1;i++)indices.push(0,i,i+1);const geometry=new THREE.BufferGeometry().setFromPoints(points);geometry.setIndex(indices);geometry.computeVertexNormals();section.geometry?.dispose();section.geometry=geometry;section.material=new THREE.MeshBasicMaterial({color:0xff3b3b,transparent:true,opacity:.78,side:THREE.DoubleSide,depthWrite:false,depthTest:false});section.renderOrder=4;sectionEdge.geometry?.dispose();sectionEdge.geometry=new THREE.BufferGeometry().setFromPoints(points);sectionEdge.material=new THREE.LineBasicMaterial({color:0x991b1b,linewidth:4,depthTest:false});sectionEdge.renderOrder=5;section.visible=showSection.value;sectionEdge.visible=showSection.value}
function fitCameraToCuttingScene(preset:CuttingPreset){const [a,b,c]=preset.plane.normal,point=new THREE.Vector3(a,b,c).multiplyScalar(preset.plane.constant/(a*a+b*b+c*c));const end=preset.camera?new THREE.Vector3(...preset.camera.position):point.clone().add(new THREE.Vector3(4.8,3.8,5.5).normalize().multiplyScalar(7));const target=preset.camera?new THREE.Vector3(...preset.camera.target):point;const from=camera.position.clone(),fromTarget=controls.target.clone(),start=performance.now();cancelAnimationFrame(cameraFrame);const move=(now:number)=>{const t=Math.min((now-start)/600,1),e=1-(1-t)**3;camera.position.lerpVectors(from,end,e);controls.target.lerpVectors(fromTarget,target,e);controls.update();if(t<1)cameraFrame=requestAnimationFrame(move)};cameraFrame=requestAnimationFrame(move)}
function loadCuttingPreset(preset:CuttingPreset){activePreset.value=preset.id;nextTick(()=>{if(!ready)initScene();if(selected.value!==preset.shape)selected.value=preset.shape!;setModel(preset.shape!);updateCuttingPlane(preset);updateSectionMesh(preset);fitCameraToCuttingScene(preset)})}
function openShape(shape:Shape){selected.value=shape;activePreset.value='';nextTick(()=>{if(!ready)initScene();setModel(shape);fitCameraToCuttingScene({id:'default',name:'',plane:{normal:[1,1,1],constant:0}})})}
function resetScene(){const preset=cuttingPresets.find(p=>p.id===activePreset.value);if(preset)fitCameraToCuttingScene(preset);else camera.position.set(5,4,6)}
function home(){dispose();selected.value=null}function resize(){if(!ready||!host.value)return;camera.aspect=host.value.clientWidth/host.value.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.value.clientWidth,host.value.clientHeight)}function renderLoop(){frame=requestAnimationFrame(renderLoop);controls?.update();renderer?.render(scene,camera)}function dispose(){cancelAnimationFrame(frame);cancelAnimationFrame(cameraFrame);if(renderer){renderer.dispose();renderer.domElement.remove()}ready=false}
onBeforeUnmount(()=>{dispose();window.removeEventListener('resize',resize)})
</script>
<template><main><header><div class="brand"><span>∠</span> 立体图形切割</div><p>观察空间几何体截面的奇妙变化</p><button v-if="selected" class="home-btn" @click="home">← 返回首页</button></header><section v-if="!selected" class="home"><div class="hero"><div><span class="eyebrow">MATH EXPLORATION</span><h1>亲手切一切，<em>看见</em>空间几何</h1><p>选择一个几何体开始。</p></div><div class="hero-shape">✦</div></div><h2>选择一个几何体开始</h2><div class="cards"><button v-for="g in geometries" :key="g.id" class="geometry-card" @click="openShape(g.id)"><span class="shape-icon">{{g.icon}}</span><strong>{{g.name}}</strong><small>{{g.subtitle}}</small></button></div></section><section v-else class="lab"><aside><div class="breadcrumb">几何 / {{selectedName}}</div><h2>{{selectedName}}切割</h2><p>选择{{ selectedName }}预设，查看真实三维求交得到的截面。</p><div class="panel"><label class="toggle"><input v-model="showSection" @change="section.visible=showSection;sectionEdge.visible=showSection" type="checkbox"> 显示切割面</label><button class="home-btn reset" @click="resetScene">重置视角</button></div><div class="panel"><h3>{{ selectedName }}预设</h3><div class="presets preset-grid"><button v-for="p in visiblePresets" :key="p.id" :class="{active:activePreset===p.id}" @click="loadCuttingPreset(p)"><span>{{p.name}}</span></button></div></div><div class="tip">💡 可继续拖动鼠标，从任意角度观察真实截面。</div></aside><div ref="host" class="viewer"><div class="viewer-label"><span></span> 真实几何截面</div><div class="controls-hint">拖拽旋转 · 滚轮缩放</div></div></section></main></template>
