import * as THREE from 'three'

export type VectorTuple = [number, number, number]
export interface CuttingPreset { id: string; name: string; shape?: 'cube'|'prism'|'triangular'|'cylinder'|'cone'; plane: { normal: VectorTuple; constant: number }; camera?: { position: VectorTuple; target: VectorTuple } }
export const EPSILON = 1e-6
const vertices: VectorTuple[] = [[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]]
const cubeEdges: [number,number][] = [[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]]

export function createPlaneFromEquation(a:number,b:number,c:number,d:number) { const length=Math.hypot(a,b,c); return new THREE.Plane(new THREE.Vector3(a,b,c).multiplyScalar(1/length),-d/length) }
export function sortPointsOnPlane(points: THREE.Vector3[], normal: THREE.Vector3) { const center=points.reduce((sum,p)=>sum.add(p),new THREE.Vector3()).multiplyScalar(1/points.length); const reference=Math.abs(normal.z)<.9?new THREE.Vector3(0,0,1):new THREE.Vector3(0,1,0); const u=new THREE.Vector3().crossVectors(reference,normal).normalize(),v=new THREE.Vector3().crossVectors(normal,u).normalize(); return [...points].sort((a,b)=>Math.atan2(a.clone().sub(center).dot(v),a.clone().sub(center).dot(u))-Math.atan2(b.clone().sub(center).dot(v),b.clone().sub(center).dot(u))) }
export function calculatePlaneCubeIntersections(normal: VectorTuple, constant:number) { const n=new THREE.Vector3(...normal), points:THREE.Vector3[]=[]; for(const [i,j] of cubeEdges){const a=new THREE.Vector3(...vertices[i]),b=new THREE.Vector3(...vertices[j]),ab=b.clone().sub(a),denominator=n.dot(ab),numerator=constant-n.dot(a); if(Math.abs(denominator)<EPSILON){if(Math.abs(numerator)<EPSILON){points.push(a,b)};continue}const t=numerator/denominator;if(t>=-EPSILON&&t<=1+EPSILON)points.push(a.add(ab.multiplyScalar(THREE.MathUtils.clamp(t,0,1))));}const unique=points.filter((point,index)=>points.findIndex(other=>other.distanceToSquared(point)<EPSILON*EPSILON)===index); return sortPointsOnPlane(unique,n.normalize()) }
export function calculatePlaneGeometryIntersections(geometry: THREE.BufferGeometry, normal: VectorTuple, constant: number) { const position=geometry.getAttribute('position'),index=geometry.getIndex(),n=new THREE.Vector3(...normal),points:THREE.Vector3[]=[]; const intersect=(a:THREE.Vector3,b:THREE.Vector3)=>{const direction=b.clone().sub(a),denominator=n.dot(direction);if(Math.abs(denominator)<EPSILON)return;const t=(constant-n.dot(a))/denominator;if(t>=-EPSILON&&t<=1+EPSILON)points.push(a.clone().add(direction.multiplyScalar(THREE.MathUtils.clamp(t,0,1))))};for(let i=0;i<(index?index.count:position.count);i+=3){const get=(offset:number)=>{const k=index?index.getX(i+offset):i+offset;return new THREE.Vector3().fromBufferAttribute(position,k)};const a=get(0),b=get(1),c=get(2);intersect(a,b);intersect(b,c);intersect(c,a)}const unique=points.filter((point,index)=>points.findIndex(other=>other.distanceToSquared(point)<EPSILON*EPSILON)===index);return sortPointsOnPlane(unique,n.normalize())}
export const cuttingPresets: CuttingPreset[] = [
 {id:'equilateral-triangle',name:'等边三角形',shape:'cube',plane:{normal:[1,1,1],constant:1}}, {id:'isosceles-triangle',name:'等腰三角形',shape:'cube',plane:{normal:[1,1,2],constant:2.5}}, {id:'acute-triangle',name:'锐角三角形',shape:'cube',plane:{normal:[1.25,10/9,1],constant:-85/36}},
 {id:'rhombus',name:'菱形',shape:'cube',plane:{normal:[1,1,2],constant:0}}, {id:'isosceles-trapezoid',name:'等腰梯形',shape:'cube',plane:{normal:[1,2,2],constant:-1.5}}, {id:'trapezoid',name:'普通梯形',shape:'cube',plane:{normal:[1,3,4],constant:-2.5}},
 {id:'square-horizontal',name:'正方形①',shape:'cube',plane:{normal:[0,0,1],constant:0}}, {id:'square-vertical',name:'正方形②',shape:'cube',plane:{normal:[1,0,0],constant:0}}, {id:'rectangle-1',name:'矩形①',shape:'cube',plane:{normal:[1,1,0],constant:.5}}, {id:'rectangle-2',name:'矩形②',shape:'cube',plane:{normal:[1,0,1],constant:.5}}, {id:'rectangle-3',name:'矩形③',shape:'cube',plane:{normal:[0,1,1],constant:.5}},
 {id:'parallelogram',name:'平行四边形',shape:'cube',plane:{normal:[1,2,3],constant:0}}, {id:'pentagon',name:'普通五边形',shape:'cube',plane:{normal:[1,1,3],constant:-15/8}}, {id:'hexagon',name:'普通六边形',shape:'cube',plane:{normal:[2,3,4],constant:0}}, {id:'regular-hexagon',name:'正六边形',shape:'cube',plane:{normal:[1,1,1],constant:0}},
 {id:'prism-rectangle',name:'矩形截面',shape:'prism',plane:{normal:[1,0,0],constant:0}}, {id:'prism-oblique',name:'斜切截面',shape:'prism',plane:{normal:[1,1,1],constant:0}},
 {id:'triangular-triangle',name:'三角形截面',shape:'triangular',plane:{normal:[0,0,1],constant:0}}, {id:'triangular-oblique',name:'斜切截面',shape:'triangular',plane:{normal:[1,1,1],constant:0}},
 {id:'cylinder-circle',name:'圆形截面',shape:'cylinder',plane:{normal:[0,1,0],constant:0}}, {id:'cylinder-ellipse',name:'椭圆截面',shape:'cylinder',plane:{normal:[1,1,0],constant:0}},
 {id:'cone-circle',name:'圆形截面',shape:'cone',plane:{normal:[0,1,0],constant:0}}, {id:'cone-ellipse',name:'椭圆截面',shape:'cone',plane:{normal:[1,1,0],constant:0}}
]
