import * as THREE from 'three'

export type VectorTuple = [number, number, number]
export interface CuttingPreset { id: string; name: string; shape?: 'cube'|'prism'|'triangular'|'cylinder'|'cone'; plane: { normal: VectorTuple; constant: number }; camera?: { position: VectorTuple; target: VectorTuple } }
export const EPSILON = 1e-6
const vertices: VectorTuple[] = [[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]]
const cubeEdges: [number,number][] = [[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]]

export function createPlaneFromEquation(a:number,b:number,c:number,d:number) { const length=Math.hypot(a,b,c); return new THREE.Plane(new THREE.Vector3(a,b,c).multiplyScalar(1/length),-d/length) }
export function sortPointsOnPlane(points: THREE.Vector3[], normal: THREE.Vector3) { const center=points.reduce((sum,p)=>sum.add(p),new THREE.Vector3()).multiplyScalar(1/points.length); const reference=Math.abs(normal.z)<.9?new THREE.Vector3(0,0,1):new THREE.Vector3(0,1,0); const u=new THREE.Vector3().crossVectors(reference,normal).normalize(),v=new THREE.Vector3().crossVectors(normal,u).normalize(); return [...points].sort((a,b)=>Math.atan2(a.clone().sub(center).dot(v),a.clone().sub(center).dot(u))-Math.atan2(b.clone().sub(center).dot(v),b.clone().sub(center).dot(u))) }
export function calculatePlaneCubeIntersections(normal: VectorTuple, constant:number) { const n=new THREE.Vector3(...normal), points:THREE.Vector3[]=[]; for(const [i,j] of cubeEdges){const a=new THREE.Vector3(...vertices[i]),b=new THREE.Vector3(...vertices[j]),ab=b.clone().sub(a),denominator=n.dot(ab),numerator=constant-n.dot(a); if(Math.abs(denominator)<EPSILON){if(Math.abs(numerator)<EPSILON){points.push(a,b)};continue}const t=numerator/denominator;if(t>=-EPSILON&&t<=1+EPSILON)points.push(a.add(ab.multiplyScalar(THREE.MathUtils.clamp(t,0,1))));}const unique=points.filter((point,index)=>points.findIndex(other=>other.distanceToSquared(point)<EPSILON*EPSILON)===index); return sortPointsOnPlane(unique,n.normalize()) }
export function calculatePlaneGeometryIntersections(geometry: THREE.BufferGeometry, normal: VectorTuple, constant: number) { const position=geometry.getAttribute('position'),index=geometry.getIndex(),n=new THREE.Vector3(...normal),points:THREE.Vector3[]=[]; const intersect=(a:THREE.Vector3,b:THREE.Vector3)=>{const direction=b.clone().sub(a),denominator=n.dot(direction);if(Math.abs(denominator)<EPSILON)return;const t=(constant-n.dot(a))/denominator;if(t>=-EPSILON&&t<=1+EPSILON)points.push(a.clone().add(direction.multiplyScalar(THREE.MathUtils.clamp(t,0,1))))};for(let i=0;i<(index?index.count:position.count);i+=3){const get=(offset:number)=>{const k=index?index.getX(i+offset):i+offset;return new THREE.Vector3().fromBufferAttribute(position,k)};const a=get(0),b=get(1),c=get(2);intersect(a,b);intersect(b,c);intersect(c,a)}const unique=points.filter((point,index)=>points.findIndex(other=>other.distanceToSquared(point)<EPSILON*EPSILON)===index);return sortPointsOnPlane(unique,n.normalize())}
